### ISSUE TITLE
Updation of readme.md file

### ISSUE THREAD

**Issue by Nikhil0-3** [milansamuel609/milansamuel609#1]
In your readme.md file please remove thqt octopus image.It is not looks good.
Since this is a professionals platform not a fish market.
So I suggest to remove that.

I would like to work on this issue,if any further changes required please let me know.l

**Comment by Nikhil0-3** [comment]
If possible make this issue as a level 3 so that I will get 35 points.
And also for hackoctofest 
Thank you.

**Comment by Nikhil0-3** [comment]
Please assign this issue to me.

**Comment by milansamuel609** [comment]
> If possible make this issue as a level 3 so that I will get 35 points. And also for hackoctofest Thank you.

@Nikhil0-3 sorry but you are getting terminated. Level is for 45 points and not for 35 points. Have a nice day a head.

**Comment by Nikhil0-3** [comment]
I have one nice image than yours please reopen it
https://raw.githubusercontent.com/sanjay-kv/sanjay-kv/main/Assets/illustration.png
Take a look

**Comment by milansamuel609** [comment]
@Nikhil0-3 
Dont change image and all. I have a task for you add the snake at the end. I have mistakenly deleted it. Add the snake at the last ok. Will you do?

**Comment by Nikhil0-3** [comment]
Ok sir

**Comment by milansamuel609** [comment]
Ok I am assigning this issue to you. Give your best shot 👍 .

**Comment by milansamuel609** [comment]
While raising the pull request kindly mention the issue number.
Like this Fixes:[#"Your number"]
